(delete 'width initial-frame-alist)
(delete 'height initial-frame-alist)
(delete 'top initial-frame-alist)
(delete 'left initial-frame-alist)
(setq initial-frame-alist (append (list
'(width . 113)
'(height . 57)
'(top . 14)
'(left . 982))
initial-frame-alist))
