(delete 'width initial-frame-alist)
(delete 'height initial-frame-alist)
(delete 'top initial-frame-alist)
(delete 'left initial-frame-alist)
(setq initial-frame-alist (append (list
'(width . 101)
'(height . 52)
'(top . 24)
'(left . 983))
initial-frame-alist))
